services:
  - type: web
    name: postgrest
    plan: free
    env: docker
    repo: https://github.com/Euxen/postgrest-participaya
    autoDeploy: true
    envVars:
      # Use Render's native database reference instead of hardcoded string
      - key: PGRST_DB_URI
        fromDatabase:
          name: scraper_db_6t74
          property: connectionString
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: scraper_db_6t74_user
      # Disable database notifications to avoid user lookup issues
      - key: PGRST_DB_CHANNEL_ENABLED
        value: "false"

databases:
  - name: scraper_db_6t74
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: from anywhere