services:
  - type: web
    plan: free
    name: postgrest
    env: docker
    autoDeploy: false
    envVars:
      - key: PGRST_DB_URI
        value: postgresql://scraper_db_6t74_user:YvckzIPxUMZwaN6gwJGZB83ju3XCoFao@dpg-cul385d6l47c73eg5gfg-a:5432/scraper_db_6t74
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: anon

databases:
  - name: postgrest-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: from anywhere
