services:
  - type: web
    plan: free
    name: postgrest
    env: docker
    autoDeploy: true   # automatically redeploy on push
    envVars:
      - key: PGRST_DB_URI
        fromDatabase:
          name: scraper_db_6t74   # <-- make sure this matches your actual Render DB
          property: connectionString
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: participaya_user

databases:
  - name: scraper_db_6t74   # <-- match your actual DB
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: from anywhere
