services:
  - type: web
    name: postgrest
    plan: free
    env: docker
    repo: https://github.com/Euxen/postgrest-participaya
    autoDeploy: true
    envVars:
      - key: PGRST_DB_URI
        fromDatabase:
          name: scraper_db_6t74
          property: connectionString
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: web_anon
      - key: PGRST_SERVER_PORT
        value: "3000"
      - key: PGRST_DB_CHANNEL_ENABLED
        value: "false"
      # Optional: Add CORS if you need it
      - key: PGRST_SERVER_CORS_ALLOWED_ORIGINS
        value: "*"

databases:
  - name: scraper_db_6t74
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: from anywhere