services:
  - type: web
    name: postgrest
    plan: free
    env: docker
    repo: https://github.com/Euxen/postgrest-participaya
    autoDeploy: true
    envVars:
      - key: PGRST_DB_URI
        value: postgresql://scraper_db_6t74_user:YvckzIPxUMZwaN6gwJGZB83ju3XCoFao@dpg-cul385d6l47c73eg5gfg-a/scraper_db_6t74
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: scraper_db_6t74_user
      - key: PGRST_DB_CHANNEL_ENABLED
        value: "false"

databases:
  - name: scraper_db_6t74
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: from anywhere