services:
  - type: web
    name: postgrest
    plan: free
    env: docker
    repo: https://github.com/Euxen/postgrest-participaya
    autoDeploy: true
    envVars:
      # Dummy connection string just to satisfy PostgREST startup
      - key: PGRST_DB_URI
        value: postgresql://dummy:dummy@localhost:5432/dummy
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: dummy

databases:
  - name: scraper_db_6t74
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: from anywhere